### ISSUE TITLE
Cypher the first Register Initialization on the bit 62 state

### ISSUE THREAD

**Issue by HugoHly** [bastianraschke/a51-cipher-simulator#1]
Hi,

I'm currently programming the A5/1 algorithm and when I used your application to compare with mine I cope with an issue.

Firstly, I thought I made a misstake because I'm studying it. 
But after analyzing my code and reviewing your code, I think I found a misstake in yours.

The issue is you use the pre-last state to evaluate the next state of the Registers Initialization.
Then, the last line don't move when she need and the rest of the generation is broken.

Have a nice day.

**Comment by bastianraschke** [comment]
Thats true, I remember now we did some shortcuts in the end. Not optimal to show to full algorithm I have to admit. Thanks for your info and feel free to to a pull request to make it correct 👍
